In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a=np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
b.shape

(2, 3)

In [ ]:
print([0,0],b[0,1],[1,0])

[0, 0] 2 [1, 0]


In [ ]:
c=np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [ ]:
d=np.ones((1,2))
print(d)

[[1. 1.]]


In [ ]:
e=np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [ ]:
f=np.eye(3)

In [ ]:
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
g=np.random.random((2,2))
print(g)

[[0.03482199 0.11344076]
 [0.56354551 0.38428276]]


In [ ]:
h= np.random.random((5,5))

In [ ]:
print(h)

[[0.98428434 0.18817877 0.40467797 0.74654896 0.03670267]
 [0.0763751  0.28077662 0.38243757 0.87706045 0.01418238]
 [0.23514348 0.8492671  0.81861046 0.21644061 0.63462409]
 [0.57415259 0.40662041 0.19910764 0.12777481 0.72405299]
 [0.85738889 0.23889833 0.15819889 0.97207125 0.29580996]]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)
print(a)

[[2 3]
 [6 7]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

2
77


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1 = a[1,:]
row_r2 = a[1:2,:]
row_r3=a[[1],:]
print(row_r1)
print(row_r2)
print(row_r3)

[5 6 7 8]
[[5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(row_r1.shape)
print(row_r2.shape)
print(row_r3.shape)

(4,)
(1, 4)
(2, 4)


In [ ]:
column_1=a[:,1]
column_2=a[:,1:2]
column_3=a[:,[1]]
print(column_1,column_1.shape)
print(column_2,column_2.shape)
print(column_3,column_3.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]
[1 4 5]


In [ ]:
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[2 2]
[2 2]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [ ]:
a[np.arange(4),b] +=10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
bool_idx =(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print(a[bool_idx])

[3 4 5 6]


In [ ]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2],dtype= np.int64)
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [ ]:
x = np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))
print(x.dot(y))
print(v @ w)
print(x @ y)

219
219
[[19 22]
 [43 50]]
219
[[19 22]
 [43 50]]
